### ISSUE TITLE
Lỗi sau khi nâng cấp module user sử dụng tool modue_c34to40

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module_c34to40#14]
Sau khi nâng cấp báo thành công xong thì khi vào trang quản trị admin sẽ không thể login được

**Comment by htuyen1994** [comment]
a copy sitekey của site cũ sang nhé.

**Comment by trinhthinhhp** [comment]
@htuyen1994 lấy csdl sang rồi update, sitekey lấy ở đâu ra nữa

**Comment by htuyen1994** [comment]
trong file congfig ý

**Comment by trinhthinhhp** [comment]
thế chú thêm cái này vào hướng dẫn đi, trong hướng dẫn ko có  :dancer:

**Comment by htuyen1994** [comment]
thêm vào r đó, chờ a thảo cập nhật request là xong
