### ISSUE TITLE
Module shops bị lỗi SQLSTATE[42000] sau khi sử dụng tool nâng cấp

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module_c34to40#15]
Module shops lỗi cảnh báo khi thực hiện "Thực hiện nâng cấp" của module c34to40
Nên chú ý: SQLSTATE[42000]: Syntax error or access violation: 1110 Column 'vi_title' specified twice

**Comment by htuyen1994** [comment]
fixed
