### ISSUE TITLE
Lỗi module download sau khi nâng cấp từ bản 3 lên 4

### ISSUE THREAD

**Issue by trinhthinhhp** [nukeviet/module_c34to40#16]
Module download lỗi không show dc chủ đề con của chủ đề cha ngay tại trang main.
Khi vào chủ đề con hoặc trang chi tiết nhân được cảnh báo:
 Nên chú ý: Undefined index: in file /modules/download/functions.php on line 106

**Comment by htuyen1994** [comment]
fixed
