### ISSUE TITLE
Lỗi trang trắng khi nâng cấp module news từ Nv3.4 lên Nv4RC3

### ISSUE THREAD

**Issue by anhtrangxua5** [nukeviet/module_c34to40#20]
Mình làm theo hướng dẫn trên https://github.com/nukeviet/module_c34to40 nhưng khi đến đoạn Truy cập đường dẫn http:/domain/c34to40/news/  (hoặc shop) thì bị trang trắng, xin nhờ được giúp đỡ,

Mình chạy trên localhost xampp, 

Xin cảm ơn

**Comment by hoaquynhtim99** [comment]
Bạn kiểm tra lại bước này
```
Import các bảng dữ liệu module NukeViet 3 vào CSDL chứa các bảng của NukeViet 4
```

Và bước này

```
Mở modules/c34to40/function.php. Tìm đến dòng define( 'NV3_PREFIX', 'nv3' ); và thay ‘nv3’ bằng tiếp đầu tố bảng dữ liệu NukeViet 3 của bạn.
```

Khi đó cần chắc chắn phải tồn tai bảng `nv3_vi_modules` hoặc `prefix_vi_modules` nếu bạn đổi prefix, nếu không sẽ ra trang trắng
