### ISSUE TITLE
Lỗi khi nâng cấp module news: 'nv3_vi_news_cat' doesn't exist

### ISSUE THREAD

**Issue by stormlove** [nukeviet/module_c34to40#22]
_» Lỗi copy dữ liệu chủ đề: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nv3_vi_news_cat' doesn't exist_

Trong functions.php đã khai báo:
**define('NV3_PREFIX', 'news');**
nhưng trong module_c34to40/funcs/news.php, dòng 157 lại fix cứng là nv3
**define('NV_PREFIXLANG3', 'nv3_' . NV_LANG_DATA);**
phải chăng sai ở đây?

**Comment by vuthao** [comment]
Cám ơn @stormlove đã báo lỗi và phát hiện đúng chỗ lỗi.
Mình đã sửa lại: https://github.com/nukeviet/module_c34to40/commit/82d9c93e5d49dec2655e2e37c8cd430930f3671a
