### ISSUE TITLE
Lỗi nâng cấp module download

### ISSUE THREAD

**Issue by motcaiten** [nukeviet/module_c34to40#23]
Sau khi nhấn "Thực hiện nâng cấp" thì load về http://domain.com/download/.

Vào admin kiểm tra thì không lấy được chuyên mục

**Comment by vuthao** [comment]
Mình đã sửa lại, bạn tiến hành nâng cấp thử lại xem nhé

**Comment by motcaiten** [comment]
OK rồi anh.
