### ISSUE TITLE
PDO Không Tương Thích

### ISSUE THREAD

**Issue by namson93** [nukeviet/module_c34to40#24]
Khi cài nukeviet 4.0 thì bị báo lổi phiên bản PHP và PDO. e có nhờ bên Hosting hỗ trợ thì được thông báo đã nâng cấp lên 5.5 và thêm PDO nhưng khi setup lại thì phần DPO báo là không tương thích
http://luuniemdocdao.com/info.php
Mong a hỗ trợ.xin cảm ơn

**Comment by vuthao** [comment]
Nếu nhà cung cấp hosting của bạn không làm được điều này, nên chuyển nhà cung cấp khác nhé.
