### ISSUE TITLE
[news] Phát sinh lỗi : thiếu topic,thiếu nhóm tin, bị dừng với DB lớn ...

### ISSUE THREAD

**Issue by anhyeuviolet** [nukeviet/module_c34to40#5]
Mình convert thì phát sinh vài lỗi sau :
+ Phần theo dòng sự kiện, convert xong, khi vào admin/index.php?language=vi&nv=news&op=topics thì trắng trơn. Phải copy y chang tên của topic cũ và tạo mới bên 4.x thì các topic này tự nhận lại các bài viết. Nếu không thì khi xem bài chi tiết, phần theo dòng sự kiện chỉ trả về url đến topic//.

+ Phần nhóm tin không chuyển sang được. Không ảnh hưởng lắm nhưng có vẻ ảnh hưởng đến block headline. Block này ko chạy trên data convert, mình đang thăm do xem là do DB hay do block lỗi.

+ DB của mình có khoảng 5k bài viết, không lớn lắm nhưng chắc chạy hết 30s là bị timeout và trắng trang.

+ Một số trường hợp, quá trình convert bị dừng tại một bài viết nhất định ( đến đúng bài đó thì dừng ) và báo lỗi kiểu như "SQLSTATE[42S02]: Base table or view not found...." và báo một table nào đó trong DB mới không tồn tại. Nếu tìm và xoá các bài viết ngay chỗ bị dừng thì sẽ convert tiếp bình thường.

+ Về Prefix : Hiện cơ chế prefix vẫn còn cứng trong file, cần phải sửa thủ công trong php mới có thể convert. Hy vọng sẽ có cải tiến cho phép tự điền prefix trong bản tiếp theo.

+ Về tác giả : Có vẻ tất cả tác giả đều được dồn về Master Admin ? ( Mình chưa test trên web nhiều user nên ko dám chắc ). Nếu có thể, hy vọng modules cũng cho phép chuyển hợp lý các bài viết đến các user mới ( hoặc cho phép tạo mới ) trong quá trình convert, vì nhiều khi là bài của CTV và dồn hết vào thì cũng khó.

+ Về nguồn tin : Nhiều nguồn tin cũng không được chuyển sang đầy đủ trong bài viết.

-------------
Tạm thời nhiêu đó. Hy vọng BQT có thể xem xét.

**Comment by lehongphongdtu** [comment]
Với Modules News tôi bị lỗi
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.nv3_vi_news_cat' doesn't exist

Với Modules Download tôi bị lôi 
Lỗi máy chủ

500

**Comment by vuthao** [comment]
@lehongphongdtu Vui lòng thực hiện cẩn thận lại theo hướng dẫn, nhiều khả năng bạn chưa import CSDL của bản NukeViet 3 vào, hoặc chưa khai báo đúng thông số:
```
Mở modules/c34to40/function.php. Tìm đến dòng define( 'NV3_PREFIX', 'nv3' ); và thay ‘nv3’ bằng tiếp đầu tố bảng dữ liệu NukeViet 3 của bạn.
```

**Comment by lehongphongdtu** [comment]
Thanks bạn, tôi đã làm từng bươc, để tôi kiểm tra lần nữ rồi sẽ báo cáo tại đây.

**Comment by lehongphongdtu** [comment]
tôi đã kiểm tra lại toàn bộ các bước đúng như hướng dẫn
Các bước thực hiện:

Cài đặt NukeViet 4 (phiên bản mới nhất) và đăng nhập quản trị tối cao.
Import các bảng dữ liệu module NukeViet 3 vào CSDL chứa các bảng của NukeViet 4
Cài đặt module c34to40 bằng gói cài đặt (Hoặc download trên https://github.com/nukeviet/module_c34to40, giải nén và copy tương ứng với cấu trúc của NukeViet 4)
Mở modules/c34to40/function.php. Tìm đến dòng define( 'NV3_PREFIX', 'nv3' ); và thay ‘nv3’ bằng tiếp đầu tố bảng dữ liệu NukeViet 3 của bạn.
1. Nâng cấp dữ liệu module Users (Tài khoản)

Xóa hết tất cả tài khoản thành viên (nếu có), chỉ dữ lại tài khoản quản trị tối cao.
Truy cập đường dẫn http:/domain/c34to40/users/
Chọn module muốn nâng cấp (users), sau đó nhấn “Thực hiện nâng cấp”
Đợi đến khi nhận được thông báo thành công.
2. Nâng cấp dữ liệu module News (Tin tức)

Xóa hết tất cả dữ liệu module news hoặc module ảo của news (nếu có) (Có thể thực hiện thao tác “Cài lại”)
Copy thư mục uploads/news (hoặc uploads/module-ao-news) ở NukeViet 3 vào thư mục tương ứng của NukeViet 4
Truy cập đường dẫn http:/domain/c34to40/news/
Chọn module lấy dữ liệu (Module của NukeViet 3), sau đó chọn module muốn nâng cấp (ở NukeViet 4), sau đó nhấn “Thực hiện nâng cấp”
Đợi đến khi nhận được thông báo thành công.
3. Nâng cấp dữ liệu module Download

Xóa hết tất cả dữ liệu module download hoặc module ảo của download (nếu có) (Có thể thực hiện thao tác “Cài lại”)
Copy thư mục uploads/download (hoặc uploads/module-ao-download) ở NukeViet 3 vào thư mục tương ứng của NukeViet 4
Truy cập đường dẫn http:/domain/c34to40/download/
Chọn module lấy dữ liệu (Module của NukeViet 3), sau đó chọn module muốn nâng cấp (ở NukeViet 4), sau đó nhấn “Thực hiện nâng cấp”
Đợi đến khi nhận được thông báo thành công.
---------------------------------------------------------------------------------------------------------------------------
Sau khi cài xong tôi làm đúng như trên (THỰC HIỆN TRÊN LOCALHOST)
Đối với Modules Users (Tôi không cần nâng cấp)
Đối với Modules News
gặp lỗi
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.nv3_vi_news_cat' doesn't exist

(tiền tố đầu trong CSDL của tôi là nv32) còn khi cài nukeviet 4rc1 thì để nguyên nv4
Còn với Modules Download 
Lỗi máy chủ

500
rất mong các Đ/C trợ giúp

**Comment by htuyen1994** [comment]
Phần theo dòng sự kiện -> xong

Phần nhóm tin -> xong

Nguồn tin :-> xong

DB của mình có khoảng 5k bài viết, không lớn lắm nhưng chắc chạy hết 30s là bị timeout và trắng trang. -> chưa test

Một số trường hợp, quá trình convert bị dừng tại một bài viết nhất định ( đến đúng bài đó thì dừng ) và báo lỗi kiểu như "SQLSTATE[42S02]: Base table or view not found...." và báo một table nào đó trong DB mới không tồn tại. Nếu tìm và xoá các bài viết ngay chỗ bị dừng thì sẽ convert tiếp bình thường.

Về Prefix : Hiện cơ chế prefix vẫn còn cứng trong file, cần phải sửa thủ công trong php mới có thể convert. Hy vọng sẽ có cải tiến cho phép tự điền prefix trong bản tiếp theo. -> chưa làm

Về tác giả : Có vẻ tất cả tác giả đều được dồn về Master Admin ? ( Mình chưa test trên web nhiều user nên ko dám chắc ). Nếu có thể, hy vọng modules cũng cho phép chuyển hợp lý các bài viết đến các user mới ( hoặc cho phép tạo mới ) trong quá trình convert, vì nhiều khi là bài của CTV và dồn hết vào thì cũng khó.

**Comment by vuthao** [comment]
Mình đã bổ sung thêm đoạn code set_time_limit để không bị timeout nữa.
